"""System and evaluation prompt templates for Adaptive RAG."""

from prompts.rag_prompts import (
    QUERY_SECURITY_SYSTEM_PROMPT,
    QUERY_ANALYZER_SYSTEM_PROMPT,
    RETRIEVAL_GRADER_SYSTEM_PROMPT,
    QUESTION_REWRITER_SYSTEM_PROMPT,
    GENERATOR_SYSTEM_PROMPT,
    GENERATOR_REGENERATION_SYSTEM_PROMPT,
    HALLUCINATION_DETECTOR_SYSTEM_PROMPT,
    ANSWER_RELEVANCE_GRADER_SYSTEM_PROMPT,
    OUTPUT_ANSWER_SECURITY_SYSTEM_PROMPT,
    EXTERNAL_SEARCH_SYSTEM_PROMPT,
)

__all__ = [
    "QUERY_SECURITY_SYSTEM_PROMPT",
    "QUERY_ANALYZER_SYSTEM_PROMPT",
    "RETRIEVAL_GRADER_SYSTEM_PROMPT",
    "QUESTION_REWRITER_SYSTEM_PROMPT",
    "GENERATOR_SYSTEM_PROMPT",
    "GENERATOR_REGENERATION_SYSTEM_PROMPT",
    "HALLUCINATION_DETECTOR_SYSTEM_PROMPT",
    "ANSWER_RELEVANCE_GRADER_SYSTEM_PROMPT",
    "OUTPUT_ANSWER_SECURITY_SYSTEM_PROMPT",
    "EXTERNAL_SEARCH_SYSTEM_PROMPT",
]
